name: CI

on:
  push:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://www.myget.org/F/itsokto/api/v2/package
      env:
        NUGET_AUTH_TOKEN: ${{secrets.MYGET_API_TOKEN}}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack -c Release -o out

    - name: Push
      run: dotnet nuget push ./out/*.nupkg
